version: 2.1

orbs:
  win: circleci/windows@2
  docker: circleci/docker@1
  k8s: digitalocean/k8s@0.1.1

jobs:
  build:
   executor: win/default
   steps:
     - checkout
     - run:
        name: build dotnet project
        command: dotnet build ./Identity-Service
     
  dockerhub-deploy:
    executor: docker/docker
    steps:
     - setup_remote_docker
     - checkout
     - docker/check
     - docker/build:
        image: redeamerz/lifelinks-identity-service
        path: ./Identity-Service
        docker-context: ./Identity-Service
        tag: latest
     - docker/build:
        image: redeamerz/lifelinks-identity-service
        path: ./Identity-Service
        docker-context: ./Identity-Service
        tag: $CIRCLE_SHA1
     - docker/push:
        image: redeamerz/lifelinks-identity-service
        tag: 'latest,$CIRCLE_SHA1'

  kubernetes-deploy:
    executor: docker/docker
    steps:
      - checkout
      - k8s/install
      - k8s/initialize:
          cluster: lifelinks-cluster
      - run:
          name: kubernetes apply schema
          command: kubectl apply -f kubernetes
      - run:
          name: kubernetes rollout update
          command: kubectl set image deployments/identityservice identityservice=docker.io/redeamerz/lifelinks-identity-service:$CIRCLE_SHA1 -n lifelinks
    

workflows:
  build-and-publish:
    jobs:
      - build
      - dockerhub-deploy:
          context: Development
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - kubernetes-deploy:
          context: KubernetesCluster
          requires:
            - dockerhub-deploy
          filters:
            branches:
              only:
                - main